### ISSUE TITLE
No Interfaces found on this device issue.... unzipped the file and when starting the program gets this and cant do a wifi scan

### ISSUE THREAD

**Issue by yoyoz10tt** [TheBATeam/Batch-WI-FI-Brute-Forcer#23]
![image](https://github.com/user-attachments/assets/da91185f-d485-4dda-becc-c4125c181633)

**Comment by lioen-dev** [comment]
this usually occurs because the device is not on the english language setting or the interface scan is using "Wi-Fi" rather than "WiFi". you can change the code in your file to fix this yourself or use my fork which has the issue fixed until the developers come out with a better solution. 

https://github.com/lioen-dev/Batch-WI-FI-Brute-Forcer

**Comment by lioen-dev** [comment]
please close the issue if your problem has been resolved :)

**Comment by yoyoz10tt** [comment]
![image](https://github.com/user-attachments/assets/ae817f68-8ea0-4567-bd91-13c437cc60dd)

redownloaded the app and that was what happend

my windows language is set to english and after i found the issue i tried to change (in the source code) Wi-Fi To WiFi But that didint work :(

**Comment by yoyoz10tt** [comment]
Thanks :)
